### ISSUE TITLE
React 17 Support?

### ISSUE THREAD

**Issue by hughrawlinson** [layonez/use-request-animation-frame#1]
I'm looking at using this in react 17, but the peer dependency specifies a range that doesn't include it. What do you think about adding it?

**Comment by layonez** [comment]
👋 @hughrawlinson thank you for your feedback 
If I understood correctly in terms of this hook this would only require to patch peerDepencies prop in package.json to include new major versions as there were no breaking changes in new react

I pushed new package version, so annoying message should go away now

**Comment by hughrawlinson** [comment]
Nice, thanks!
